# Generated by Django 5.1.2 on 2024-12-02 20:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0003_alter_participant_id_alter_room_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='quizSubject',
            new_name='quiz_subject',
        ),
        migrations.RemoveField(
            model_name='room',
            name='timer',
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField()),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='room.room')),
            ],
        ),
        migrations.DeleteModel(
            name='Participant',
        ),
    ]
