# Generated by Django 5.1.2 on 2024-12-02 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0004_rename_quizsubject_room_quiz_subject_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Question',
        ),
    ]
