# Generated by Django 5.1.2 on 2024-12-09 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0006_room_questions'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='timer',
            field=models.IntegerField(default=0),
        ),
    ]
