# Generated by Django 5.1.2 on 2024-10-19 17:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('status', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('score', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('text', models.CharField(max_length=255)),
                ('correctAnswer', models.CharField(max_length=255)),
                ('dificulty', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('subjectArea', models.CharField(max_length=255)),
                ('questions', models.CharField(max_length=255)),
                ('timeLimit', models.IntegerField()),
                ('currentQuestionIndex', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='rest_api.question')),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('quizSubject', models.CharField(max_length=255)),
                ('timer', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('role', models.CharField(max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name='Book',
        ),
        migrations.AddField(
            model_name='participant',
            name='roomId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rest_api.room'),
        ),
        migrations.AddField(
            model_name='invitation',
            name='roomId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rest_api.room'),
        ),
        migrations.AddField(
            model_name='participant',
            name='userId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rest_api.user'),
        ),
        migrations.AddField(
            model_name='invitation',
            name='receiverId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_invitations', to='rest_api.user'),
        ),
        migrations.AddField(
            model_name='invitation',
            name='senderId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_invitations', to='rest_api.user'),
        ),
    ]
