# Generated by Django 5.1.2 on 2024-10-28 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0003_roles_alter_user_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participant',
            name='roomId',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='userId',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='currentQuestionIndex',
        ),
        migrations.RemoveField(
            model_name='user',
            name='role',
        ),
        migrations.DeleteModel(
            name='Invitation',
        ),
        migrations.DeleteModel(
            name='Room',
        ),
        migrations.DeleteModel(
            name='Participant',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
        migrations.DeleteModel(
            name='Quiz',
        ),
        migrations.DeleteModel(
            name='Roles',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
