# Generated by Django 5.1.2 on 2024-10-28 17:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('text', models.CharField(max_length=255)),
                ('correctAnswer', models.CharField(max_length=255)),
                ('dificulty', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('subjectArea', models.CharField(max_length=255)),
                ('questions', models.CharField(max_length=255)),
                ('timeLimit', models.IntegerField()),
                ('currentQuestionIndex', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='quiz.question')),
            ],
        ),
    ]
