# Generated by Django 5.1.2 on 2024-12-02 21:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
        ('room', '0005_delete_question'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='correctAnswer',
        ),
        migrations.RemoveField(
            model_name='question',
            name='dificulty',
        ),
        migrations.RemoveField(
            model_name='question',
            name='text',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='currentQuestionIndex',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='subjectArea',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='timeLimit',
        ),
        migrations.AddField(
            model_name='question',
            name='data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='quiz',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quizzes', to='room.room'),
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='questions',
        ),
        migrations.AddField(
            model_name='quiz',
            name='questions',
            field=models.ManyToManyField(related_name='quizzes', to='quiz.question'),
        ),
    ]
