# Generated by Django 5.1.2 on 2024-12-08 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_remove_quiz_questions_quiz_question'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='name',
            new_name='quiz_subject',
        ),
        migrations.DeleteModel(
            name='Quiz',
        ),
    ]
