# Generated by Django 5.1.2 on 2024-12-08 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_remove_user_role_user_data_joined_user_groups_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='wins',
            field=models.IntegerField(default=0),
        ),
    ]
