name: Django CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10' 
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run test
        run: python print()

      - name: Run unittest
        run: python print()

  deploy:
    needs: test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup virtual environment
        run: |
          python -m venv venv
          source venv/Scripts/activate
          pip install -r requirements.txt

      - name: Run migrations
        run: |
          source venv/Scripts/activate
          python manage.py migrate

      - name: Deploy application
        run: |
          ssh root@$SERVER_IP "
            cd quiz_backend/
            git pull && 
            source venv/bin/activate && 
            pip install -r requirements.txt && 
            python manage.py migrate && 
            systemctl restart quiz_backend"

