name: Django CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt


      # - name: Run tests
      #   run: |
      #     python manage.py test

  deploy:
    needs: test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH key
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Add server to known_hosts
        env:
          SERVER_IP: ${{ secrets.SERVER_IP }}
        run: |
          ssh-keyscan -H $SERVER_IP >> ~/.ssh/known_hosts

      - name: Deploy application
        env:
          SERVER_IP: ${{ secrets.SERVER_IP }}
        run: |
          ssh -i ~/.ssh/id_rsa root@$SERVER_IP "
            cd quiz_backend/
            git pull &&
            source venv/bin/activate &&
            pip install -r requirements.txt &&
            python manage.py migrate &&
            systemctl restart quiz_backend"

